version: '3'
services:
  frontend:
    restart: always
    ports:
      - "3000:3000"
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile  

  backend:
    restart: always
    ports:
      - "5000:5000"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: npm run start-dev
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s

  database:
    image: "mongo:6.0.21-jammy"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./mongo_data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret